package projecteuler

import scala.annotation.tailrec

// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.
object P002 extends App {

  def lazilySumEvenValuedFibonacciUntil(max: Int): Int = {
    lazy val fib: Stream[Int] =
      1 #:: 2 #::  fib.zip(fib.tail).map(t => t._1 + t._2)
    fib
      .filter(_ % 2 == 0)
      .takeWhile(_ < max)
      .sum
  }

  def fibonacciUntil(max: Int): List[Int] = {
    @tailrec
    def doFibonacciUntil(acc: List[Int]): List[Int] =
      acc match {
        case h :: t if h > max => t.reverse
        case h :: hh :: t => doFibonacciUntil(h + hh :: acc)
      }

    doFibonacciUntil(2 :: 1 :: Nil)
  }

  def sumEvenValuedFibonacciUntil(max: Int): Int =
    (
      for {
        e <- fibonacciUntil(max)
        if e % 2 == 0
      } yield
        e)
      .sum

  val max = 4e6.toInt
  println(sumEvenValuedFibonacciUntil(max))
  println(lazilySumEvenValuedFibonacciUntil(max))
}
