package projecteuler

import org.scalacheck.{Gen, Prop}
import org.specs2.ScalaCheck
import org.specs2.mutable.Specification

class P003Spec extends Specification with ScalaCheck {

  "First 10 prime numbers generated by trial division" should {

    "be 2, 3, 5, 7, 13, 17, 19, 23, 29" >> {
      P003.TrialDivision.primes(P003.TrialDivision.from(2l)).take(10) ====
        2L #:: 3L #:: 5L #:: 7L #:: 11L #::
          13L #:: 17L #:: 19L #:: 23L #:: 29L #::
          Stream.empty
    }
  }

  "Greatest prime factor found by trial division and naive prime factorization" should {
    "be the same" >> {
      Prop.forAllNoShrink(Gen.choose(2, 10000)) {
        n =>
          P003.TrialDivision.largestPrimeFactorOf(n) ====
            P003.PrimeFactorization.naiveLargestPrimeFactorOf(n)
      }
    }
  }

  "Greatest prime factor found by naive and optimized prime factorizations" should {
    "be the same" >> {
      Prop.forAllNoShrink(Gen.choose(2, 200000)) {
        n =>
            P003.PrimeFactorization.naiveLargestPrimeFactorOf(n) ====
              P003.PrimeFactorization.optimizedLargestPrimeFactorOf(n)
      }
    }
  }
}
